# docker-compose-outer-app.yml (Modified)
version: '3.8'

services:
  baff-server:
    container_name: baff-service
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL : ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME : ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD : ${SPRING_DATASOURCE_PASSWORD}