spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      #show_sql: true
      format_sql: true
      default_batch_fetch_size: 100
      dialect: org.hibernate.dialect.MySQLDialect

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


springdoc:
  swagger-ui:
    path: /swagger-ui.html # 기본 경로, 변경하지 않았다면 이대로
    disable-swagger-default-url: true # 기본 URL 비활성화 (권장)
    display-request-duration: true # 요청 시간 표시
  api-docs:
    path: /v3/api-docs # API 문서 JSON 경로

openai:
  api:
    key: ${OPENAI_SECRET_KEY}
  chat:
    model: gpt-3.5-turbo
  embedding:
    model: text-embedding-ada-002
